### PR TITLE
Created two new Projectile classes.

### PR DESCRIPTION
**Pull request by FlorisXll**

### CODE REVIEW

**Comment by NielsWarnars** [comment]
Maybe change the JDoc a bit, but for the rest it looks good

**Comment by NielsWarnars** [comment]
Like: "This class represents a Bubble object that the player is able to shoot." -->
* Class representing a Bubble objects that
* the player can shoot at.

etc.

**Comment by FlorisXll** [comment]
Didnt pay much attention to that kind of detail since it has to be adjusted when something is added anyway, but will do the adjustment.

**Comment by jessetilro** [comment]
Seems fine to me :)

**Comment by NielsWarnars** [comment]
Merge all the things

**Pull request merged**
